name: Build

on:
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Install ProtoData from Maven to local env
      run: ./gradlew installProtoData
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Run tests with Gradle
      run: ./gradlew build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
